name: 'demo-action'
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: display dist files
        run: ls -la && ls dist/
