name: 'demo-action'
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 18.x
          cache: pnpm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: pnpm-lock.yaml

      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: display dist files
        run: ls -la && ls dist/
